### ISSUE TITLE
Asan detected memory leaks

### ISSUE THREAD

**Issue by biubiuzy** [rpm-software-management/popt#123]
```
#include <stdio.h>
#include <popt.h>
#define TAG_SET 128
int main(int argc, char **argv)
{
        int c;
        int cmd;
        poptContext context;
        struct poptOption options_table[] = {
                { "set", '\0', POPT_ARG_NONE, NULL, TAG_SET, NULL, NULL },
                { NULL, 0, 0, NULL, 0, NULL, NULL }
        };
        context =  poptGetContext("test", argc, (const char **)argv, options_table, 0);

        if ((c = poptGetNextOpt(context)) < 0)
                printf("first poptGetNextOpt error \n");

        if (c == TAG_SET)
                cmd = 1;

        while ((c=poptGetNextOpt(context)) >= 0){
        ;
        }

        poptFreeContext(context);
        return 0;
}
```

`gcc test.c -o test -fsanitize=address -lpopt`

`./test -set a`

output:

```
=================================================================
==1512257==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 2 byte(s) in 1 object(s) allocated from:
    #0 0x7f75659c55a7 in __interceptor_malloc (/usr/lib64/libasan.so.6+0xaf5a7)
    #1 0x7f756590c595 in poptGetNextOpt (/usr/lib64/libpopt.so.0+0x5595)

SUMMARY: AddressSanitizer: 2 byte(s) leaked in 1 allocation(s).
```

**Comment by biubiuzy** [comment]
https://github.com/rpm-software-management/popt/blob/8a4f26d30806521343f1f9efc75bd51b87ee22c3/src/popt.c#L1531

**Comment by syyhao1994** [comment]
@pmatilai PTAL. Thanks.
